version: "3.8"

services:
  # api service
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      # Only build development stage from Dockerfile
      target: development
    # Mount host dir to the docker container
    # Mount api directory to (:) docker container (/nestjs-chat/src/app)
    # Reflect file changes from host to container
    volumes:
      - ./api:/nestjs-chat/src/app
      - /nestjs-chat/src/app/node_modules
    # RUN debug mode: npm run start:debug --> also start your vs code debugger
    # RUN dev mode: npm run start:dev
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: this_is_jwt_123
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229

  # frontend service
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/nestjs-chat/frontend/src/app
      - /nestjs-chat/frontend/src/app/node_modules
    command: npm run start
    ports:
      - 4200:4200
    links:
      - api

  # postgres service
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432

  # postgres admin service
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
